version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 961341524098.dkr.ecr.ap-northeast-2.amazonaws.com
      - docker pull 961341524098.dkr.ecr.ap-northeast-2.amazonaws.com/nuxt-test:latest || true
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build --cache-from 961341524098.dkr.ecr.ap-northeast-2.amazonaws.com/nuxt-test:latest -t nuxt-test .
      - docker tag nuxt-test:latest 961341524098.dkr.ecr.ap-northeast-2.amazonaws.com/nuxt-test:latest
  post_build:
    commands:
      - echo "Pushing the Docker image..."
      - docker push 961341524098.dkr.ecr.ap-northeast-2.amazonaws.com/nuxt-test:latest
      - echo "Generating imagedefinitions.json..."
      - printf '[{"name":"nuxt-test","imageUri":"961341524098.dkr.ecr.ap-northeast-2.amazonaws.com/nuxt-test:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
cache:
  paths:
    - '/root/.yarn/**/*'